// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Request.proto</summary>
public static partial class RequestReflection {

  #region Descriptor
  /// <summary>File descriptor for Request.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RequestReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1SZXF1ZXN0LnByb3RvGgpVc2VyLnByb3RvGgxTdGF0dXMucHJvdG8aDk1h",
          "dGNoaW5nLnByb3RvGg1PcGVyYXRlLnByb3RvItkBCgtCYXNlUmVxdWVzdBIO",
          "CgZ1c2VySWQYASABKAUSIQoLcmVxdWVzdFR5cGUYAiABKA4yDC5SZXF1ZXN0",
          "VHlwZRIhCgtyZXF1ZXN0RGF0YRgDIAEoDjIMLlJlcXVlc3REYXRhEhUKBHVz",
          "ZXIYBCABKAsyBS5Vc2VySAASGQoGc3RhdHVzGAUgASgLMgcuU3RhdHVzSAAS",
          "HQoIbWF0Y2hpbmcYBiABKAsyCS5NYXRjaGluZ0gAEhsKB29wZXJhdGUYByAB",
          "KAsyCC5PcGVyYXRlSABCBgoEZGF0YSpJCgtSZXF1ZXN0VHlwZRIOCgpSVF9V",
          "TktOT1dOEAASDAoIUlRfTE9HSU4QARIMCghSVF9NQVRDSBACEg4KClJUX09Q",
          "RVJBVEUQAypXCgtSZXF1ZXN0RGF0YRIOCgpSRF9VTktOT1dOEAASCwoHUkRf",
          "VVNFUhABEg0KCVJEX1NUQVRVUxACEgwKCFJEX01BVENIEAMSDgoKUkRfT1BF",
          "UkFURRAEYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::UserReflection.Descriptor, global::StatusReflection.Descriptor, global::MatchingReflection.Descriptor, global::OperateReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RequestType), typeof(global::RequestData), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BaseRequest), global::BaseRequest.Parser, new[]{ "UserId", "RequestType", "RequestData", "User", "Status", "Matching", "Operate" }, new[]{ "Data" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// 请求的类型
/// </summary>
public enum RequestType {
  /// <summary>
  /// 未知请求
  /// </summary>
  [pbr::OriginalName("RT_UNKNOWN")] RtUnknown = 0,
  /// <summary>
  /// 登陆请求
  /// </summary>
  [pbr::OriginalName("RT_LOGIN")] RtLogin = 1,
  /// <summary>
  /// 匹配请求
  /// </summary>
  [pbr::OriginalName("RT_MATCH")] RtMatch = 2,
  /// <summary>
  /// operate
  /// </summary>
  [pbr::OriginalName("RT_OPERATE")] RtOperate = 3,
}

/// <summary>
/// 夹带的参数（也就是data的类型）
/// </summary>
public enum RequestData {
  /// <summary>
  /// 未知类型
  /// </summary>
  [pbr::OriginalName("RD_UNKNOWN")] RdUnknown = 0,
  /// <summary>
  /// 类型为User
  /// </summary>
  [pbr::OriginalName("RD_USER")] RdUser = 1,
  /// <summary>
  /// 类型为status
  /// </summary>
  [pbr::OriginalName("RD_STATUS")] RdStatus = 2,
  /// <summary>
  /// 类型为matching
  /// </summary>
  [pbr::OriginalName("RD_MATCH")] RdMatch = 3,
  /// <summary>
  /// 类型为Operate
  /// </summary>
  [pbr::OriginalName("RD_OPERATE")] RdOperate = 4,
}

#endregion

#region Messages
/// <summary>
/// 基础请求类型
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class BaseRequest : pb::IMessage<BaseRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BaseRequest> _parser = new pb::MessageParser<BaseRequest>(() => new BaseRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BaseRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RequestReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseRequest(BaseRequest other) : this() {
    userId_ = other.userId_;
    requestType_ = other.requestType_;
    requestData_ = other.requestData_;
    switch (other.DataCase) {
      case DataOneofCase.User:
        User = other.User.Clone();
        break;
      case DataOneofCase.Status:
        Status = other.Status.Clone();
        break;
      case DataOneofCase.Matching:
        Matching = other.Matching.Clone();
        break;
      case DataOneofCase.Operate:
        Operate = other.Operate.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseRequest Clone() {
    return new BaseRequest(this);
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 1;
  private int userId_;
  /// <summary>
  /// 是谁发送的请求(也就是userId)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  /// <summary>Field number for the "requestType" field.</summary>
  public const int RequestTypeFieldNumber = 2;
  private global::RequestType requestType_ = global::RequestType.RtUnknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RequestType RequestType {
    get { return requestType_; }
    set {
      requestType_ = value;
    }
  }

  /// <summary>Field number for the "requestData" field.</summary>
  public const int RequestDataFieldNumber = 3;
  private global::RequestData requestData_ = global::RequestData.RdUnknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RequestData RequestData {
    get { return requestData_; }
    set {
      requestData_ = value;
    }
  }

  /// <summary>Field number for the "user" field.</summary>
  public const int UserFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::User User {
    get { return dataCase_ == DataOneofCase.User ? (global::User) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.User;
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Status Status {
    get { return dataCase_ == DataOneofCase.Status ? (global::Status) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Status;
    }
  }

  /// <summary>Field number for the "matching" field.</summary>
  public const int MatchingFieldNumber = 6;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Matching Matching {
    get { return dataCase_ == DataOneofCase.Matching ? (global::Matching) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Matching;
    }
  }

  /// <summary>Field number for the "operate" field.</summary>
  public const int OperateFieldNumber = 7;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Operate Operate {
    get { return dataCase_ == DataOneofCase.Operate ? (global::Operate) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Operate;
    }
  }

  private object data_;
  /// <summary>Enum of possible cases for the "data" oneof.</summary>
  public enum DataOneofCase {
    None = 0,
    User = 4,
    Status = 5,
    Matching = 6,
    Operate = 7,
  }
  private DataOneofCase dataCase_ = DataOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DataOneofCase DataCase {
    get { return dataCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearData() {
    dataCase_ = DataOneofCase.None;
    data_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BaseRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BaseRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserId != other.UserId) return false;
    if (RequestType != other.RequestType) return false;
    if (RequestData != other.RequestData) return false;
    if (!object.Equals(User, other.User)) return false;
    if (!object.Equals(Status, other.Status)) return false;
    if (!object.Equals(Matching, other.Matching)) return false;
    if (!object.Equals(Operate, other.Operate)) return false;
    if (DataCase != other.DataCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UserId != 0) hash ^= UserId.GetHashCode();
    if (RequestType != global::RequestType.RtUnknown) hash ^= RequestType.GetHashCode();
    if (RequestData != global::RequestData.RdUnknown) hash ^= RequestData.GetHashCode();
    if (dataCase_ == DataOneofCase.User) hash ^= User.GetHashCode();
    if (dataCase_ == DataOneofCase.Status) hash ^= Status.GetHashCode();
    if (dataCase_ == DataOneofCase.Matching) hash ^= Matching.GetHashCode();
    if (dataCase_ == DataOneofCase.Operate) hash ^= Operate.GetHashCode();
    hash ^= (int) dataCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UserId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(UserId);
    }
    if (RequestType != global::RequestType.RtUnknown) {
      output.WriteRawTag(16);
      output.WriteEnum((int) RequestType);
    }
    if (RequestData != global::RequestData.RdUnknown) {
      output.WriteRawTag(24);
      output.WriteEnum((int) RequestData);
    }
    if (dataCase_ == DataOneofCase.User) {
      output.WriteRawTag(34);
      output.WriteMessage(User);
    }
    if (dataCase_ == DataOneofCase.Status) {
      output.WriteRawTag(42);
      output.WriteMessage(Status);
    }
    if (dataCase_ == DataOneofCase.Matching) {
      output.WriteRawTag(50);
      output.WriteMessage(Matching);
    }
    if (dataCase_ == DataOneofCase.Operate) {
      output.WriteRawTag(58);
      output.WriteMessage(Operate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UserId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(UserId);
    }
    if (RequestType != global::RequestType.RtUnknown) {
      output.WriteRawTag(16);
      output.WriteEnum((int) RequestType);
    }
    if (RequestData != global::RequestData.RdUnknown) {
      output.WriteRawTag(24);
      output.WriteEnum((int) RequestData);
    }
    if (dataCase_ == DataOneofCase.User) {
      output.WriteRawTag(34);
      output.WriteMessage(User);
    }
    if (dataCase_ == DataOneofCase.Status) {
      output.WriteRawTag(42);
      output.WriteMessage(Status);
    }
    if (dataCase_ == DataOneofCase.Matching) {
      output.WriteRawTag(50);
      output.WriteMessage(Matching);
    }
    if (dataCase_ == DataOneofCase.Operate) {
      output.WriteRawTag(58);
      output.WriteMessage(Operate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UserId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserId);
    }
    if (RequestType != global::RequestType.RtUnknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestType);
    }
    if (RequestData != global::RequestData.RdUnknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestData);
    }
    if (dataCase_ == DataOneofCase.User) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
    }
    if (dataCase_ == DataOneofCase.Status) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
    }
    if (dataCase_ == DataOneofCase.Matching) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Matching);
    }
    if (dataCase_ == DataOneofCase.Operate) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Operate);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BaseRequest other) {
    if (other == null) {
      return;
    }
    if (other.UserId != 0) {
      UserId = other.UserId;
    }
    if (other.RequestType != global::RequestType.RtUnknown) {
      RequestType = other.RequestType;
    }
    if (other.RequestData != global::RequestData.RdUnknown) {
      RequestData = other.RequestData;
    }
    switch (other.DataCase) {
      case DataOneofCase.User:
        if (User == null) {
          User = new global::User();
        }
        User.MergeFrom(other.User);
        break;
      case DataOneofCase.Status:
        if (Status == null) {
          Status = new global::Status();
        }
        Status.MergeFrom(other.Status);
        break;
      case DataOneofCase.Matching:
        if (Matching == null) {
          Matching = new global::Matching();
        }
        Matching.MergeFrom(other.Matching);
        break;
      case DataOneofCase.Operate:
        if (Operate == null) {
          Operate = new global::Operate();
        }
        Operate.MergeFrom(other.Operate);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          UserId = input.ReadInt32();
          break;
        }
        case 16: {
          RequestType = (global::RequestType) input.ReadEnum();
          break;
        }
        case 24: {
          RequestData = (global::RequestData) input.ReadEnum();
          break;
        }
        case 34: {
          global::User subBuilder = new global::User();
          if (dataCase_ == DataOneofCase.User) {
            subBuilder.MergeFrom(User);
          }
          input.ReadMessage(subBuilder);
          User = subBuilder;
          break;
        }
        case 42: {
          global::Status subBuilder = new global::Status();
          if (dataCase_ == DataOneofCase.Status) {
            subBuilder.MergeFrom(Status);
          }
          input.ReadMessage(subBuilder);
          Status = subBuilder;
          break;
        }
        case 50: {
          global::Matching subBuilder = new global::Matching();
          if (dataCase_ == DataOneofCase.Matching) {
            subBuilder.MergeFrom(Matching);
          }
          input.ReadMessage(subBuilder);
          Matching = subBuilder;
          break;
        }
        case 58: {
          global::Operate subBuilder = new global::Operate();
          if (dataCase_ == DataOneofCase.Operate) {
            subBuilder.MergeFrom(Operate);
          }
          input.ReadMessage(subBuilder);
          Operate = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          UserId = input.ReadInt32();
          break;
        }
        case 16: {
          RequestType = (global::RequestType) input.ReadEnum();
          break;
        }
        case 24: {
          RequestData = (global::RequestData) input.ReadEnum();
          break;
        }
        case 34: {
          global::User subBuilder = new global::User();
          if (dataCase_ == DataOneofCase.User) {
            subBuilder.MergeFrom(User);
          }
          input.ReadMessage(subBuilder);
          User = subBuilder;
          break;
        }
        case 42: {
          global::Status subBuilder = new global::Status();
          if (dataCase_ == DataOneofCase.Status) {
            subBuilder.MergeFrom(Status);
          }
          input.ReadMessage(subBuilder);
          Status = subBuilder;
          break;
        }
        case 50: {
          global::Matching subBuilder = new global::Matching();
          if (dataCase_ == DataOneofCase.Matching) {
            subBuilder.MergeFrom(Matching);
          }
          input.ReadMessage(subBuilder);
          Matching = subBuilder;
          break;
        }
        case 58: {
          global::Operate subBuilder = new global::Operate();
          if (dataCase_ == DataOneofCase.Operate) {
            subBuilder.MergeFrom(Operate);
          }
          input.ReadMessage(subBuilder);
          Operate = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
