// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Response.proto</summary>
public static partial class ResponseReflection {

  #region Descriptor
  /// <summary>File descriptor for Response.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResponseReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5SZXNwb25zZS5wcm90bxoKVXNlci5wcm90bxoMU3RhdHVzLnByb3RvGg5N",
          "YXRjaGluZy5wcm90bxoNT3BlcmF0ZS5wcm90bxoTQ2hhc2luZ0ZyYW1lcy5w",
          "cm90byKHAgoMQmFzZVJlc3BvbnNlEg4KBnVzZXJJZBgBIAEoBRIjCgxyZXNw",
          "b25zZVR5cGUYAiABKA4yDS5SZXNwb25zZVR5cGUSIwoMcmVzcG9uc2VEYXRh",
          "GAMgASgOMg0uUmVzcG9uc2VEYXRhEhUKBHVzZXIYBCABKAsyBS5Vc2VySAAS",
          "GQoGc3RhdHVzGAUgASgLMgcuU3RhdHVzSAASHQoIbWF0Y2hpbmcYBiABKAsy",
          "CS5NYXRjaGluZ0gAEhsKB29wZXJhdGUYByABKAsyCC5PcGVyYXRlSAASJwoN",
          "Y2hhc2luZ0ZyYW1lcxgIIAEoCzIOLkNoYXNpbmdGcmFtZXNIAEIGCgRkYXRh",
          "KkoKDFJlc3BvbnNlVHlwZRIOCgpSVF9VTktOT1dOEAASDAoIUlRfTE9HSU4Q",
          "ARIMCghSVF9NQVRDSBACEg4KClJUX09QRVJBVEUQAypuCgxSZXNwb25zZURh",
          "dGESDgoKUkRfVU5LTk9XThAAEgsKB1JEX1VTRVIQARINCglSRF9TVEFUVVMQ",
          "AhIMCghSRF9NQVRDSBADEg4KClJEX09QRVJBVEUQBBIUChBSRF9DSEFTSU5H",
          "RlJBTUVTEAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::UserReflection.Descriptor, global::StatusReflection.Descriptor, global::MatchingReflection.Descriptor, global::OperateReflection.Descriptor, global::ChasingFramesReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ResponseType), typeof(global::ResponseData), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BaseResponse), global::BaseResponse.Parser, new[]{ "UserId", "ResponseType", "ResponseData", "User", "Status", "Matching", "Operate", "ChasingFrames" }, new[]{ "Data" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// 请求的类型
/// </summary>
public enum ResponseType {
  /// <summary>
  /// 未知响应
  /// </summary>
  [pbr::OriginalName("RT_UNKNOWN")] RtUnknown = 0,
  /// <summary>
  /// 登陆响应
  /// </summary>
  [pbr::OriginalName("RT_LOGIN")] RtLogin = 1,
  /// <summary>
  /// 匹配响应
  /// </summary>
  [pbr::OriginalName("RT_MATCH")] RtMatch = 2,
  /// <summary>
  /// operate
  /// </summary>
  [pbr::OriginalName("RT_OPERATE")] RtOperate = 3,
}

/// <summary>
/// 夹带的参数（也就是data的类型）
/// </summary>
public enum ResponseData {
  /// <summary>
  /// 未知类型
  /// </summary>
  [pbr::OriginalName("RD_UNKNOWN")] RdUnknown = 0,
  /// <summary>
  /// 类型为User
  /// </summary>
  [pbr::OriginalName("RD_USER")] RdUser = 1,
  /// <summary>
  /// 类型为status
  /// </summary>
  [pbr::OriginalName("RD_STATUS")] RdStatus = 2,
  /// <summary>
  /// 类型为matching
  /// </summary>
  [pbr::OriginalName("RD_MATCH")] RdMatch = 3,
  /// <summary>
  /// 类型为operate
  /// </summary>
  [pbr::OriginalName("RD_OPERATE")] RdOperate = 4,
  /// <summary>
  /// 类型为ChasingFrames
  /// </summary>
  [pbr::OriginalName("RD_CHASINGFRAMES")] RdChasingframes = 5,
}

#endregion

#region Messages
/// <summary>
/// 基础请求类型
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class BaseResponse : pb::IMessage<BaseResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BaseResponse> _parser = new pb::MessageParser<BaseResponse>(() => new BaseResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BaseResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResponseReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseResponse(BaseResponse other) : this() {
    userId_ = other.userId_;
    responseType_ = other.responseType_;
    responseData_ = other.responseData_;
    switch (other.DataCase) {
      case DataOneofCase.User:
        User = other.User.Clone();
        break;
      case DataOneofCase.Status:
        Status = other.Status.Clone();
        break;
      case DataOneofCase.Matching:
        Matching = other.Matching.Clone();
        break;
      case DataOneofCase.Operate:
        Operate = other.Operate.Clone();
        break;
      case DataOneofCase.ChasingFrames:
        ChasingFrames = other.ChasingFrames.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BaseResponse Clone() {
    return new BaseResponse(this);
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 1;
  private int userId_;
  /// <summary>
  /// 是谁发送的请求(也就是userId)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  /// <summary>Field number for the "responseType" field.</summary>
  public const int ResponseTypeFieldNumber = 2;
  private global::ResponseType responseType_ = global::ResponseType.RtUnknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ResponseType ResponseType {
    get { return responseType_; }
    set {
      responseType_ = value;
    }
  }

  /// <summary>Field number for the "responseData" field.</summary>
  public const int ResponseDataFieldNumber = 3;
  private global::ResponseData responseData_ = global::ResponseData.RdUnknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ResponseData ResponseData {
    get { return responseData_; }
    set {
      responseData_ = value;
    }
  }

  /// <summary>Field number for the "user" field.</summary>
  public const int UserFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::User User {
    get { return dataCase_ == DataOneofCase.User ? (global::User) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.User;
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Status Status {
    get { return dataCase_ == DataOneofCase.Status ? (global::Status) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Status;
    }
  }

  /// <summary>Field number for the "matching" field.</summary>
  public const int MatchingFieldNumber = 6;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Matching Matching {
    get { return dataCase_ == DataOneofCase.Matching ? (global::Matching) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Matching;
    }
  }

  /// <summary>Field number for the "operate" field.</summary>
  public const int OperateFieldNumber = 7;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Operate Operate {
    get { return dataCase_ == DataOneofCase.Operate ? (global::Operate) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Operate;
    }
  }

  /// <summary>Field number for the "chasingFrames" field.</summary>
  public const int ChasingFramesFieldNumber = 8;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ChasingFrames ChasingFrames {
    get { return dataCase_ == DataOneofCase.ChasingFrames ? (global::ChasingFrames) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.ChasingFrames;
    }
  }

  private object data_;
  /// <summary>Enum of possible cases for the "data" oneof.</summary>
  public enum DataOneofCase {
    None = 0,
    User = 4,
    Status = 5,
    Matching = 6,
    Operate = 7,
    ChasingFrames = 8,
  }
  private DataOneofCase dataCase_ = DataOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DataOneofCase DataCase {
    get { return dataCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearData() {
    dataCase_ = DataOneofCase.None;
    data_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BaseResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BaseResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserId != other.UserId) return false;
    if (ResponseType != other.ResponseType) return false;
    if (ResponseData != other.ResponseData) return false;
    if (!object.Equals(User, other.User)) return false;
    if (!object.Equals(Status, other.Status)) return false;
    if (!object.Equals(Matching, other.Matching)) return false;
    if (!object.Equals(Operate, other.Operate)) return false;
    if (!object.Equals(ChasingFrames, other.ChasingFrames)) return false;
    if (DataCase != other.DataCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UserId != 0) hash ^= UserId.GetHashCode();
    if (ResponseType != global::ResponseType.RtUnknown) hash ^= ResponseType.GetHashCode();
    if (ResponseData != global::ResponseData.RdUnknown) hash ^= ResponseData.GetHashCode();
    if (dataCase_ == DataOneofCase.User) hash ^= User.GetHashCode();
    if (dataCase_ == DataOneofCase.Status) hash ^= Status.GetHashCode();
    if (dataCase_ == DataOneofCase.Matching) hash ^= Matching.GetHashCode();
    if (dataCase_ == DataOneofCase.Operate) hash ^= Operate.GetHashCode();
    if (dataCase_ == DataOneofCase.ChasingFrames) hash ^= ChasingFrames.GetHashCode();
    hash ^= (int) dataCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UserId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(UserId);
    }
    if (ResponseType != global::ResponseType.RtUnknown) {
      output.WriteRawTag(16);
      output.WriteEnum((int) ResponseType);
    }
    if (ResponseData != global::ResponseData.RdUnknown) {
      output.WriteRawTag(24);
      output.WriteEnum((int) ResponseData);
    }
    if (dataCase_ == DataOneofCase.User) {
      output.WriteRawTag(34);
      output.WriteMessage(User);
    }
    if (dataCase_ == DataOneofCase.Status) {
      output.WriteRawTag(42);
      output.WriteMessage(Status);
    }
    if (dataCase_ == DataOneofCase.Matching) {
      output.WriteRawTag(50);
      output.WriteMessage(Matching);
    }
    if (dataCase_ == DataOneofCase.Operate) {
      output.WriteRawTag(58);
      output.WriteMessage(Operate);
    }
    if (dataCase_ == DataOneofCase.ChasingFrames) {
      output.WriteRawTag(66);
      output.WriteMessage(ChasingFrames);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UserId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(UserId);
    }
    if (ResponseType != global::ResponseType.RtUnknown) {
      output.WriteRawTag(16);
      output.WriteEnum((int) ResponseType);
    }
    if (ResponseData != global::ResponseData.RdUnknown) {
      output.WriteRawTag(24);
      output.WriteEnum((int) ResponseData);
    }
    if (dataCase_ == DataOneofCase.User) {
      output.WriteRawTag(34);
      output.WriteMessage(User);
    }
    if (dataCase_ == DataOneofCase.Status) {
      output.WriteRawTag(42);
      output.WriteMessage(Status);
    }
    if (dataCase_ == DataOneofCase.Matching) {
      output.WriteRawTag(50);
      output.WriteMessage(Matching);
    }
    if (dataCase_ == DataOneofCase.Operate) {
      output.WriteRawTag(58);
      output.WriteMessage(Operate);
    }
    if (dataCase_ == DataOneofCase.ChasingFrames) {
      output.WriteRawTag(66);
      output.WriteMessage(ChasingFrames);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UserId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserId);
    }
    if (ResponseType != global::ResponseType.RtUnknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseType);
    }
    if (ResponseData != global::ResponseData.RdUnknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseData);
    }
    if (dataCase_ == DataOneofCase.User) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
    }
    if (dataCase_ == DataOneofCase.Status) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
    }
    if (dataCase_ == DataOneofCase.Matching) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Matching);
    }
    if (dataCase_ == DataOneofCase.Operate) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Operate);
    }
    if (dataCase_ == DataOneofCase.ChasingFrames) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChasingFrames);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BaseResponse other) {
    if (other == null) {
      return;
    }
    if (other.UserId != 0) {
      UserId = other.UserId;
    }
    if (other.ResponseType != global::ResponseType.RtUnknown) {
      ResponseType = other.ResponseType;
    }
    if (other.ResponseData != global::ResponseData.RdUnknown) {
      ResponseData = other.ResponseData;
    }
    switch (other.DataCase) {
      case DataOneofCase.User:
        if (User == null) {
          User = new global::User();
        }
        User.MergeFrom(other.User);
        break;
      case DataOneofCase.Status:
        if (Status == null) {
          Status = new global::Status();
        }
        Status.MergeFrom(other.Status);
        break;
      case DataOneofCase.Matching:
        if (Matching == null) {
          Matching = new global::Matching();
        }
        Matching.MergeFrom(other.Matching);
        break;
      case DataOneofCase.Operate:
        if (Operate == null) {
          Operate = new global::Operate();
        }
        Operate.MergeFrom(other.Operate);
        break;
      case DataOneofCase.ChasingFrames:
        if (ChasingFrames == null) {
          ChasingFrames = new global::ChasingFrames();
        }
        ChasingFrames.MergeFrom(other.ChasingFrames);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          UserId = input.ReadInt32();
          break;
        }
        case 16: {
          ResponseType = (global::ResponseType) input.ReadEnum();
          break;
        }
        case 24: {
          ResponseData = (global::ResponseData) input.ReadEnum();
          break;
        }
        case 34: {
          global::User subBuilder = new global::User();
          if (dataCase_ == DataOneofCase.User) {
            subBuilder.MergeFrom(User);
          }
          input.ReadMessage(subBuilder);
          User = subBuilder;
          break;
        }
        case 42: {
          global::Status subBuilder = new global::Status();
          if (dataCase_ == DataOneofCase.Status) {
            subBuilder.MergeFrom(Status);
          }
          input.ReadMessage(subBuilder);
          Status = subBuilder;
          break;
        }
        case 50: {
          global::Matching subBuilder = new global::Matching();
          if (dataCase_ == DataOneofCase.Matching) {
            subBuilder.MergeFrom(Matching);
          }
          input.ReadMessage(subBuilder);
          Matching = subBuilder;
          break;
        }
        case 58: {
          global::Operate subBuilder = new global::Operate();
          if (dataCase_ == DataOneofCase.Operate) {
            subBuilder.MergeFrom(Operate);
          }
          input.ReadMessage(subBuilder);
          Operate = subBuilder;
          break;
        }
        case 66: {
          global::ChasingFrames subBuilder = new global::ChasingFrames();
          if (dataCase_ == DataOneofCase.ChasingFrames) {
            subBuilder.MergeFrom(ChasingFrames);
          }
          input.ReadMessage(subBuilder);
          ChasingFrames = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          UserId = input.ReadInt32();
          break;
        }
        case 16: {
          ResponseType = (global::ResponseType) input.ReadEnum();
          break;
        }
        case 24: {
          ResponseData = (global::ResponseData) input.ReadEnum();
          break;
        }
        case 34: {
          global::User subBuilder = new global::User();
          if (dataCase_ == DataOneofCase.User) {
            subBuilder.MergeFrom(User);
          }
          input.ReadMessage(subBuilder);
          User = subBuilder;
          break;
        }
        case 42: {
          global::Status subBuilder = new global::Status();
          if (dataCase_ == DataOneofCase.Status) {
            subBuilder.MergeFrom(Status);
          }
          input.ReadMessage(subBuilder);
          Status = subBuilder;
          break;
        }
        case 50: {
          global::Matching subBuilder = new global::Matching();
          if (dataCase_ == DataOneofCase.Matching) {
            subBuilder.MergeFrom(Matching);
          }
          input.ReadMessage(subBuilder);
          Matching = subBuilder;
          break;
        }
        case 58: {
          global::Operate subBuilder = new global::Operate();
          if (dataCase_ == DataOneofCase.Operate) {
            subBuilder.MergeFrom(Operate);
          }
          input.ReadMessage(subBuilder);
          Operate = subBuilder;
          break;
        }
        case 66: {
          global::ChasingFrames subBuilder = new global::ChasingFrames();
          if (dataCase_ == DataOneofCase.ChasingFrames) {
            subBuilder.MergeFrom(ChasingFrames);
          }
          input.ReadMessage(subBuilder);
          ChasingFrames = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
